url: "https://tinkerdome.com"
baseurl: ""
title: "Tinker Dome"

destination: html

exclude:
- ".gitignore"
- "tinkerdome.code-workspace"
- ".jekyll-cache"

collections:
  videoPosts:
    output: true
